export const API_ENDPOINTS = {
 USER: "User",
 SHTETI: "Shteti",
 QYTETI: "Qyteti",
 GJINIA: "Gjinia",
 ARTIKULLI: "Artikulli",
 TIPIARTIKULLIT: "TipiArtikullit",
 LLOJIARTIKULIT: "LlojiArtikullit",
 LOKACIONI: "Lokacioni",
 HOTEL: "Hoteli",
 RESTORANT: "Restaurant",
 ROOM: "Dhoma",
 LLOJIDHOMES: "LlojiDhomes",
 MENU: "Menu",
 MENUITEM: "MenuItem",
 SPONSOR: "Sponsors",
 RESERVATIONS: "Rezervimi",
 ARRITJET: "Achievements",
 FAKTE: "HoteliFakte",
 CONTACT: "ContactUs",
};
